# Source: /home/greyadmin/cbcr/build/range/deployments/template.py
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-google-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-google-a
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: rtr1-svc
      labels:
        app: dns-google-a
    spec:
      containers:
      - env:
        - name: IP_ADDR
          value: 8.8.8.8
        - name: LEN
          value: '8'
        - name: GATEWAY
          value: 8.0.0.1
        - name: INT
          value: net1
        image: master:5000/bind
        name: dns-google-a
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/bind
          name: google-public-dns-a-google-com
      initContainers: []
      volumes:
      - name: google-public-dns-a-google-com
        nfs:
          path: /configs/dns/recursive
          server: storage


