# Source: /home/greyadmin/cbcr/build/range/deployments/template.py
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntp-europe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ntp-europe
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: rtr2-svc
      labels:
        app: ntp-europe
    spec:
      containers:
      - env:
        - name: IP_ADDR
          value: 89.120.166.8
        - name: LEN
          value: '8'
        - name: GATEWAY
          value: 89.0.0.1
        - name: INT
          value: net1
        image: master:5000/ntpd
        name: ntp-europe
        securityContext:
          privileged: true
        volumeMounts: []
      initContainers: []
      volumes: []


