# Source: /home/greyadmin/cbcr/build/range/deployments/template.py
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtr-04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtr-04
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: bgp, bgp, rtr4-svc, external
      labels:
        app: rtr-04
    spec:
      containers:
      - env: []
        image: master:5000/frr
        name: rtr-04
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/frr
          name: rtr-04
      initContainers: []
      volumes:
      - name: rtr-04
        nfs:
          path: /configs/network/rtr-04
          server: storage


