# Source: /home/greyadmin/cbcr/build/range/deployments/template.py
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp-google
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp-google
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: rtr1-svc
      labels:
        app: smtp-google
    spec:
      containers:
      - env:
        - name: IP_ADDR
          value: 74.125.21.26
        - name: LEN
          value: '8'
        - name: GATEWAY
          value: 74.0.0.1
        - name: INT
          value: net1
        image: master:5000/smtp
        name: smtp-google
        securityContext:
          privileged: true
        volumeMounts: []
      initContainers: []
      volumes: []


