# Source: /home/greyadmin/cbcr/build/range/deployments/template.py
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn-vpn
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: rtr1-svc
      labels:
        app: vpn-vpn
    spec:
      containers:
      - env:
        - name: IP_ADDR
          value: 34.202.89.42
        - name: LEN
          value: '8'
        - name: GATEWAY
          value: 34.0.0.1
        - name: INT
          value: net1
        - name: OPEN_VPN_CMD
          value: ovpn_run
        image: master:5000/openvpn
        name: vpn-vpn
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/openvpn
          name: vpn-com
      initContainers:
      - command:
        - ovpn_genconfig
        - -u
        - udp://vpn.com
        image: master:5000/openvpn
        name: vpn-vpn-vpn-genconfig
        volumeMounts:
        - mountPath: /etc/openvpn
          name: vpn-com
      - command:
        - ovpn_initpki
        - nopass
        image: master:5000/openvpn
        name: vpn-vpn-vpn-initpki
        volumeMounts:
        - mountPath: /etc/openvpn
          name: vpn-com
      - command:
        - easyrsa
        - build-client-full
        - vpn
        - nopass
        image: master:5000/openvpn
        name: vpn-vpn-vpn-build-client
        volumeMounts:
        - mountPath: /etc/openvpn
          name: vpn-com
      - command:
        - ovpn_getclient
        - vpn
        - '>'
        - /configs/vpn/vpn.ovpn
        image: master:5000/openvpn
        name: vpn-vpn-vpn-get-client
        volumeMounts:
        - mountPath: /etc/openvpn
          name: vpn-com
      volumes:
      - name: vpn-com
        nfs:
          path: /configs/vpn/vpn.com
          server: storage


