# Source: /home/greyadmin/cbcr/build/range/deployments/template.py
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-org
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuln-org
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: rtr1-svc
      labels:
        app: vuln-org
    spec:
      containers:
      - env:
        - name: IP_ADDR
          value: 128.143.18.14
        - name: LEN
          value: '8'
        - name: GATEWAY
          value: 128.0.0.1
        - name: INT
          value: net1
        image: master:5000/metasploit-vuln-svc-emu
        name: vuln-org
        securityContext:
          privileged: true
        volumeMounts: []
      initContainers: []
      volumes: []


