# Source: /home/greyadmin/cbcr/build/range/deployments/template.py
apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-trademe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www-trademe
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: rtr4-svc
      labels:
        app: www-trademe
    spec:
      containers:
      - env:
        - name: IP_ADDR
          value: 203.162.72.2
        - name: LEN
          value: '8'
        - name: GATEWAY
          value: 203.0.0.1
        - name: INT
          value: net1
        image: master:5000/nginx
        name: www-trademe
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: trademe-co-nz
      initContainers: []
      volumes:
      - name: trademe-co-nz
        nfs:
          path: /configs/web/trademe.co.nz
          server: storage


